### ISSUE TITLE
--scsi0 local:cloudinit won't work with qm set or create

### ISSUE THREAD

**Issue by mzhaqs** [jiangcuo/Proxmox-Port#72]
**Describe the bug**
--scsi0 local:cloudinit used to work fine before the recent update

**To Reproduce**
qm create 90107 --name pimox-1-kube-vm-1 --ostype l26 --cpu host --scsihw virtio-scsi-pci --scsi0 local:cloudinit --boot order=virtio0 --onboot 1 --bios ovmf --efidisk0 local:0

**Error**
unable to parse directory volume name 'cloudinit'

**Expected behavior**
VM should get created

**Screenshots**
N/A

**ENV (please complete the following information):**
 - OS: Raspberry pi bookwork
 - ARCH: arm64
 - Version 8.1.7

**Additional context**
I can create an IDE drive but don't how to use it with my raspy 4 b 8 gb.
Also seems to be working in PVE 7 on bullseye

**Comment by jiangcuo** [comment]
This  issue exist on x86_64 too.

**Comment by nikos445** [comment]
any workaround?

**Comment by mzhaqs** [comment]
I just moved to 7 for now. But I believe rolling back to 8.1.3 will work as well.

**Comment by nikos445** [comment]
I used Sata for cloud-init it worked (maybe a workaround for some people)...

Also when booting from ISO/CD then the SCSI of IMG that you boot shall be set to no. **2** when created or else it wont boot.

**Comment by jiangcuo** [comment]
This issue has been fixed in the new commit.
https://git.proxmox.com/?p=qemu-server.git;a=commit;h=7e2065956f4cc5c15f947f0df431f46861b0a0c0

**Comment by mzhaqs** [comment]
Issue seems to still exists
![image](https://github.com/jiangcuo/Proxmox-Port/assets/3624240/29e51ef4-3c0b-486e-97d9-4859c46ca324)

**Comment by mzhaqs** [comment]
Issue seems to still exist. This is from a fresh installation.
![image](https://github.com/jiangcuo/Proxmox-Port/assets/3624240/630cfcb0-8d3f-4976-b97c-d5275f369683)

**Comment by SuperKali** [comment]
@mzhaqs @jiangcuo I have the same problem, on nanopc t6 only on the fresh installation the second node not have this problem

**Comment by SuperKali** [comment]
![image](https://github.com/jiangcuo/Proxmox-Port/assets/19473898/04d46898-026f-4035-bdf2-82113a0b0ef8)

**Comment by SuperKali** [comment]
@jiangcuo @mzhaqs I had to compile myself the qemu-server and add this https://github.com/jiangcuo/qemu-server/commit/7e2065956f4cc5c15f947f0df431f46861b0a0c0 on the branch arm64, now work fine, can you apply this patch and release it on the repo?
![image](https://github.com/jiangcuo/Proxmox-Port/assets/19473898/eeb32523-8a6a-475d-aa9f-cc99a5b69eef)

For arm64 users can use this package compiled by me at the moment:
[qemu-server_8.1.1+port3_arm64.zip](https://github.com/jiangcuo/Proxmox-Port/files/15133404/qemu-server_8.1.1%2Bport3_arm64.zip)
